#pragma once

enum class InputAction
{
    // Dev Menu
    DEV_MENU_KEY,

    // Default Mappings
    RETURN_KEY,

    // P1
    P1_ENTER_KEY,

    P1_MENU_UP_KEY,
    P1_MENU_LEFT_KEY,
    P1_MENU_DOWN_KEY,
    P1_MENU_RIGHT_KEY,

    P1_GAME_UP_KEY,
    P1_GAME_LEFT_KEY,
    P1_GAME_DOWN_KEY,
    P1_GAME_RIGHT_KEY,

    P1_SCAN_CARD,
    P1_NUMPAD_0,
    P1_NUMPAD_1,
    P1_NUMPAD_2,
    P1_NUMPAD_3,
    P1_NUMPAD_4,
    P1_NUMPAD_5,
    P1_NUMPAD_6,
    P1_NUMPAD_7,
    P1_NUMPAD_8,
    P1_NUMPAD_9,

    // P2
    P2_ENTER_KEY,

    P2_MENU_UP_KEY,
    P2_MENU_LEFT_KEY,
    P2_MENU_DOWN_KEY,
    P2_MENU_RIGHT_KEY,

    P2_GAME_UP_KEY,
    P2_GAME_LEFT_KEY,
    P2_GAME_DOWN_KEY,
    P2_GAME_RIGHT_KEY,

    P2_SCAN_CARD,
    P2_NUMPAD_0,
    P2_NUMPAD_1,
    P2_NUMPAD_2,
    P2_NUMPAD_3,
    P2_NUMPAD_4,
    P2_NUMPAD_5,
    P2_NUMPAD_6,
    P2_NUMPAD_7,
    P2_NUMPAD_8,
    P2_NUMPAD_9,
};